### PR TITLE
Make primaryStage injectable CDI bean

### LINKED ISSUE #80: Make primaryStage injectable CDI bean
Similar to (#53: Make javafx.application.HostServices injectable)

### PR DESCRIPTION
**Pull request by Eng-Fouad**
Resolves #80

### CODE REVIEW

**Comment by CodeSimcoe** [comment]
Hello, looks good, can you add a test case for this ?

**Comment by CodeSimcoe** [comment]
Also the doc shall be updated :)

**Comment by Eng-Fouad** [comment]
> Hello, looks good, can you add a test case for this ?

> Also the doc shall be updated :)

Done.

Do you know why the tests fail?

**Comment by CodeSimcoe** [comment]
Having a look

**Comment by CodeSimcoe** [comment]
A thing that occurred to me is that an application can have multiple stages. It lacks semantics to indicate that we intend to inject the primary stage, maybe we shall add a @Qualifer.

**Comment by Eng-Fouad** [comment]
> A thing that occurred to me is that an application can have multiple stages. It lacks semantics to indicate that we intend to inject the primary stage, maybe we shall add a @Qualifer.

It is true that an FX application can have multiple stages, but there is only a single stage that is instantiated by JavaFX runtime at startup, that's why it is called primary stage.

**Comment by Eng-Fouad** [comment]
> Do you know why the tests fail?

I got help from Quarkus team on Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/CDI.20producer.20method.20is.20not.20called/near/476999834

Tests passes now.

**Comment by CodeSimcoe** [comment]
Why not just provide a static accessor from an utility class, that would ease usage.
I don't see real relevance in injecting the accessor.

If stage is not created yet, accessor returns null (or throws an IllegalState), otherwise returns the primary stage instance.

**Comment by Eng-Fouad** [comment]
> Why not just provide a static accessor from an utility class, that would ease usage. I don't see real relevance in injecting the accessor.
> 
> If stage is not created yet, accessor returns null (or throws an IllegalState), otherwise returns the primary stage instance.

That's another option. However, that would not match how we access other objects using this extension (CDI for HostServices vs static field/method for primaryStage). It's up to you :)

**Comment by Eng-Fouad** [comment]
> Yes indeed, if we want injection I don't see a better idea yet.

How about adding `primaryStage` to `FxViewRepository`?

**Comment by CodeSimcoe** [comment]
> > Yes indeed, if we want injection I don't see a better idea yet.
> 
> How about adding `primaryStage` to `FxViewRepository`?

Sounds like a good idea !

**Comment by CodeSimcoe** [comment]
#87

**Pull request closed without merging**
