### PR TITLE
Quarkus main

### PR DESCRIPTION
**Pull request by CodeSimcoe**
Comparable to picocli extension, provide a default launcher.
Can be overridden in app by using a custom @QuarkusMain

### CODE REVIEW

**Comment by maxandersen** [comment]
Looks good. Can't try yet as just on mobile but I'm curious what happens if one have both picocli and fx enabled and both entry points available. Do they manage to fail build to state one need to be explicit ?

**Comment by CodeSimcoe** [comment]
With both extensions build is in error :

`[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.6.7:build (default) on project quarkus-using-fx-extension: Failed to build quarkus application: io.qu
arkus.builder.ChainBuildException: Multiple producers of item class io.quarkus.deployment.builditem.QuarkusApplicationClassBuildItem (io.quarkiverse.fx.deployment.QuarkusFxExt
ensionProcessor#quarkusFxLauncher): This is the location of the conflicting producer (io.quarkus.picocli.deployment.PicocliProcessor#picocliRunner). Use -Dquarkus.builder.log-conflict-cause=true to see the full stacktrace. -> [Help 1]`

**Comment by maxandersen** [comment]
Hmmm. Thats problematic as using picocli parsing together with jfx is perfectly valid usecase.

**Comment by maxandersen** [comment]
so i'm not sure if this is the fx extension or the https://github.com/CodeSimcoe/quarkus-using-fx-extension repo (we should have such sample into this repo imo) example that is behaving weird - but it seem to swallow exceptions:

Like, if I add picocli extension and nothing else I still get a starting javafx app but only when closing I get this exception:

```
2024-01-31 07:50:01,639 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): jakarta.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class java.lang.Object] and qualifiers [[@io.quarkus.picocli.runtime.annotations.TopCommand()]]
        at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:288)
        at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
        at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
        at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory.create(DefaultPicocliCommandLineFactory.java:43)
        at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory_ClientProxy.create(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer.picocliCommandLine(PicocliCommandLineProducer.java:23)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_khVRGvi_eaW5dhdY-YKZYLyj_sA_Bean.doCreate(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_khVRGvi_eaW5dhdY-YKZYLyj_sA_Bean.create(Unknown Source)
```

and similar fetching anything from api I get errors about dns erros for swapi.dev (which is weird as that works fine from command line curl):

```
2024-01-31 07:53:31,187 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-0) Mutiny had to drop the following exception: jakarta.ws.rs.ProcessingException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'swapi.dev' [A(1)] and search domain query for configured domains failed as well: [localdomain]
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$2.accept(ClientSendRequestHandler.java:199)
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$2.accept(ClientSendRequestHandler.java:191)
        at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onFailure(UniCallbackSubscriber.java:62)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
        at org.jboss.resteasy.reactive.client.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:37)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86)
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:184)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:66)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
        at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
        at io.vertx.core.http.impl.HttpClientImpl.lambda$doRequest$6(HttpClientImpl.java:689)
        at io.vertx.core.net.impl.pool.Endpoint.lambda$getConnection$0(Endpoint.java:52)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:162)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:123)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
        at io.vertx.core.impl.ContextBase.emit(ContextBase.java:297)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool$ConnectFailed$1.run(SimpleConnectionPool.java:381)
        at io.vertx.core.net.impl.pool.Task.runNextTasks(Task.java:43)
        at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:82)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:245)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.acquire(SimpleConnectionPool.java:640)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.acquire(SharedClientHttpStreamEndpoint.java:166)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.requestConnection2(SharedClientHttpStreamEndpoint.java:173)
        at io.vertx.core.http.impl.ClientHttpEndpointBase.requestConnection(ClientHttpEndpointBase.java:49)
        at io.vertx.core.net.impl.pool.Endpoint.getConnection(Endpoint.java:41)
        at io.vertx.core.net.impl.pool.ConnectionManager.getConnection(ConnectionManager.java:51)
        at io.vertx.core.http.impl.HttpClientImpl.doRequest(HttpClientImpl.java:662)
        at io.vertx.core.http.impl.HttpClientImpl.doRequest(HttpClientImpl.java:627)
        at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:458)
        at org.jboss.resteasy.reactive.client.impl.ClientImpl$LazyVertx$LazyHttpClient.request(ClientImpl.java:754)
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$5.lambda$apply$0(ClientSendRequestHandler.java:432)
        at org.jboss.resteasy.reactive.client.AsyncResultUni.subscribe(AsyncResultUni.java:31)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.UniOnItemConsume$UniOnItemComsumeProcessor.onItem(UniOnItemConsume.java:43)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemConsume.subscribe(UniOnItemConsume.java:30)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.handle(ClientSendRequestHandler.java:93)
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.handle(ClientSendRequestHandler.java:65)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:231)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:38)
        at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:35)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:259)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'swapi.dev' [A(1)] and search domain query for configured domains failed as well: [localdomain]
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1097)
        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1044)
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:432)
        at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:66)
        at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:500)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(Defaule.java:118)
        at io.netty.resolver.dns.DnsQueryContext.finishFailure(DnsQueryContext.java:348)
        at io.netty.resolver.dns.DnsQueryContext.onQueryWriteCompletion(DnsQueryContext.java:276)
        at io.netty.resolver.dns.DnsQueryContext.access$700(DnsQueryContext.java:45)
        at io.netty.resolver.dns.DnsQueryContext$4.operationComplete(DnsQueryContext.java:267)
        at io.netty.resolver.dns.DnsQueryContext$4.operationComplete(DnsQueryContext.java:264)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
        at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
        at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:732)
        at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:317)
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:297)
        at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:158)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
        at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
        at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
        at io.netty.resolver.dns.DnsNameResolver.flushQueries(DnsNameResolver.java:1329)
        at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:375)
        at io.netty.resolver.dns.DnsResolveContext.doSearchDomainQuery(DnsResolveContext.java:298)
        at io.netty.resolver.dns.DnsAddressResolveContext.doSearchDomainQuery(DnsAddressResolveContext.java:98)
        at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:261)
        at io.netty.resolver.dns.DnsNameResolver.resolveNow(DnsNameResolver.java:1227)
        at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1213)
        at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached(DnsNameResolver.java:1155)
        at io.netty.resolver.dns.DnsNameResolver.doResolveUncached(DnsNameResolver.java:1057)
        at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:999)
        at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:831)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:100)
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:66)
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:51)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:171)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:148)
        at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:152)
        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:103)
        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:89)
        at io.vertx.core.net.impl.NetClientImpl.connectInternal2(NetClientImpl.java:304)
        at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$2(NetClientImpl.java:270)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
        at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:164)
        at io.vertx.core.net.impl.NetClientImpl.connectInternal(NetClientImpl.java:268)
        at io.vertx.core.http.impl.HttpChannelConnector.connect(HttpChannelConnector.java:90)
        at io.vertx.core.http.impl.HttpChannelConnector.httpConnect(HttpChannelConnector.java:148)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.connect(SharedClientHttpStreamEndpoint.java:82)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.connect(SimpleConnectionPool.java:254)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool$Acquire$3.run(SimpleConnectionPool.java:596)
        ... 49 more
Caused by: io.netty.resolver.dns.DnsNameResolverException: [27195: /[2001:4860:4860:0:0:0:0:8844]:53] DefaultDnsQuestion(swapi.dev. IN A) failed to send a query '27195' via UDP (no stack trace available)
Caused by: java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
        at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:953)
        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:914)
        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:872)
        at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:297)
        at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:143)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
        at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
        at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
        at io.netty.resolver.dns.DnsNameResolver.flushQueries(DnsNameResolver.java:1329)
        at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:375)
        at io.netty.resolver.dns.DnsResolveContext.doSearchDomainQuery(DnsResolveContext.java:298)
        at io.netty.resolver.dns.DnsAddressResolveContext.doSearchDomainQuery(DnsAddressResolveContext.java:98)
        at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:261)
        at io.netty.resolver.dns.DnsNameResolver.resolveNow(DnsNameResolver.java:1227)
        at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1213)
        at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached(DnsNameResolver.java:1155)
        at io.netty.resolver.dns.DnsNameResolver.doResolveUncached(DnsNameResolver.java:1057)
        at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:999)
        at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:831)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:100)
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:66)
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:51)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddrlver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:171)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:148)
        at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:152)
        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:103)
        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:89)
        at io.vertx.core.net.impl.NetClientImpl.connectInternal2(NetClientImpl.java:304)
        at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$2(NetClientImpl.java:270)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
        at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:164)
        at io.vertx.core.net.impl.NetClientImpl.connectInternal(NetClientImpl.java:268)
        at io.vertx.core.http.impl.HttpChannelConnector.connect(HttpChannelConnector.java:90)
        at io.vertx.core.http.impl.HttpChannelConnector.httpConnect(HttpChannelConnector.java:148)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.connect(SharedClientHttpStreamEndpoint.java:82)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.connect(SimpleConnectionPool.java:254)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool$Acquire$3.run(SimpleConnectionPool.java:596)
        at io.vertx.core.net.impl.pool.Task.runNextTasks(Task.java:43)
        at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:82)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:245)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.acquire(SimpleConnectionPool.java:640)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.acquire(SharedClientHttpStreamEndpoint.java:166)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.requestConnection2(SharedClientHttpStreamEndpoint.java:173)
        at io.vertx.core.http.impl.ClientHttpEndpointBase.requestConnection(ClientHttpEndpointBase.java:49)
        at io.vertx.core.net.impl.pool.Endpoint.getConnection(Endpoint.java:41)
        at io.vertx.core.net.impl.pool.ConnectionManager.getConnection(ConnectionManager.java:51)
        at io.vertx.core.http.impl.HttpClientImpl.doRequest(HttpClientImpl.java:662)
        at io.vertx.core.http.impl.HttpClientImpl.doRequest(HttpClientImpl.java:627)
        at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:458)
        at org.jboss.resteasy.reactive.client.impl.ClientImpl$LazyVertx$LazyHttpClient.request(ClientImpl.java:754)
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$5.lambda$apply$0(ClientSendRequestHandler.java:432)
        at org.jboss.resteasy.reactive.client.AsyncResultUni.subscribe(AsyncResultUni.java:31)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.UniOnItemConsume$UniOnItemComsumeProcessor.onItem(UniOnItemConsume.java:43)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemConsume.subscribe(UniOnItemConsume.java:30)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.handle(ClientSendRequestHandler.java:93)
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.handle(ClientSendRequestHandler.java:65)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:231)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:38)
        at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:35)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:259)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by CodeSimcoe** [comment]
Concerning this issue, i have created an issue
https://github.com/quarkusio/quarkus/issues/38553

Also made a sample that shows the limitaton
https://github.com/CodeSimcoe/quarkus-main-clash

**Comment by CodeSimcoe** [comment]
I've made a few adjustements.

Item `QuarkusApplicationClassBuildItem` is now `@Overridable`.

Let's recap possible use cases.

Using Quarkus FX alone (or without any other `QuarkusApplicationClassBuildItem` producer) :
- A launcher is added : QuarkusFxApplication that will take care of launching the JavaFX application
- If a custom @QuarkusMain is present, nothing will be added : you'll have to take care of calling `javafx.application.Application::launch`

Using Quakus FX along with a `QuarkusApplicationClassBuildItem` producer, such as picocli :
- QuarkusFxApplication is not added (picocli will take precedence)
- If a custom @QuarkusMain is present, nothing is added (also for picocli), user will have to define its own @QuarkusMain

This seems pretty reasonable to ease most use cases.
In conflict cases, Quarkus FX will be overridden, and you'll have to provide a way to call the `javafx.application.Application::launch`

**Pull request merged**
